name: evaluacion_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  connection_status_bar: ^1.1.6
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  firma_digital:
    git:
      url: https://gitlab.it-strategy.mx/luis-lopez/flutter/flutter-signature-component
      ref: development
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  intl: ^0.17.0
  objectbox: ^2.2.0
  objectbox_flutter_libs: ^2.2.0
  objectbox_generator: ^2.2.0
  path_provider: ^2.1.0


dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
