// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/subordinados_model_ob.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8859643581238265966),
      name: 'SubordinadosGestorModelOb',
      lastPropertyId: const IdUid(6, 5009145535624666910),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4207610994464934763),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 6129241503767985969),
            name: 'amat',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1996484664361307574),
            name: 'apat',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4915826658972063960),
            name: 'nombre',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7683359589001133200),
            name: 'idTeam',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5009145535624666910),
            name: 'idUsuarioSeg',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8859643581238265966),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SubordinadosGestorModelOb: EntityDefinition<SubordinadosGestorModelOb>(
        model: _entities[0],
        toOneRelations: (SubordinadosGestorModelOb object) => [],
        toManyRelations: (SubordinadosGestorModelOb object) => {},
        getId: (SubordinadosGestorModelOb object) => object.id,
        setId: (SubordinadosGestorModelOb object, int id) {
          if (object.id != id) {
            throw ArgumentError(
                'Field SubordinadosGestorModelOb.id is read-only '
                '(final or getter-only) and it was declared to be self-assigned. '
                'However, the currently inserted object (.id=${object.id}) '
                "doesn't match the inserted ID (ID $id). "
                'You must assign an ID before calling [box.put()].');
          }
        },
        objectToFB: (SubordinadosGestorModelOb object, fb.Builder fbb) {
          final amatOffset = fbb.writeString(object.amat);
          final apatOffset = fbb.writeString(object.apat);
          final nombreOffset = fbb.writeString(object.nombre);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, amatOffset);
          fbb.addOffset(2, apatOffset);
          fbb.addOffset(3, nombreOffset);
          fbb.addInt64(4, object.idTeam);
          fbb.addInt64(5, object.idUsuarioSeg);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final amatParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final apatParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nombreParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final idUsuarioSegParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final idTeamParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = SubordinadosGestorModelOb(
              amat: amatParam,
              apat: apatParam,
              id: idParam,
              nombre: nombreParam,
              idUsuarioSeg: idUsuarioSegParam,
              idTeam: idTeamParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SubordinadosGestorModelOb] entity fields to define ObjectBox queries.
class SubordinadosGestorModelOb_ {
  /// see [SubordinadosGestorModelOb.id]
  static final id = QueryIntegerProperty<SubordinadosGestorModelOb>(
      _entities[0].properties[0]);

  /// see [SubordinadosGestorModelOb.amat]
  static final amat = QueryStringProperty<SubordinadosGestorModelOb>(
      _entities[0].properties[1]);

  /// see [SubordinadosGestorModelOb.apat]
  static final apat = QueryStringProperty<SubordinadosGestorModelOb>(
      _entities[0].properties[2]);

  /// see [SubordinadosGestorModelOb.nombre]
  static final nombre = QueryStringProperty<SubordinadosGestorModelOb>(
      _entities[0].properties[3]);

  /// see [SubordinadosGestorModelOb.idTeam]
  static final idTeam = QueryIntegerProperty<SubordinadosGestorModelOb>(
      _entities[0].properties[4]);

  /// see [SubordinadosGestorModelOb.idUsuarioSeg]
  static final idUsuarioSeg = QueryIntegerProperty<SubordinadosGestorModelOb>(
      _entities[0].properties[5]);
}
